### ISSUE TITLE
NameError: name 'Ks' is not defined

### ISSUE THREAD

**Issue by Y5neKO** [nixpal/shellsilo#1]
Traceback (most recent call last):
  File "shellsilo.py", line 69, in <module>
    ks = Ks(KS_ARCH_X86, KS_MODE_32)
NameError: name 'Ks' is not defined
![image](https://github.com/user-attachments/assets/3eec5a83-11c8-4c8a-87ff-0a8fe14ad297)

**Comment by nixpal** [comment]
You need to install keystone.
pip3 install keystone
https://pypi.org/project/keystone/

**Comment by Y5neKO** [comment]
> You need to install keystone. pip3 install keystone https://pypi.org/project/keystone/

Yes, I have installed it, but it still gives an error. Is it a problem with the Python version? What is your Python version?
![image](https://github.com/user-attachments/assets/0470321c-fb98-4fce-9052-1d8819c2ea15)

**Comment by nixpal** [comment]
can you try this to check if both environment are the same for your python
import sys
print(sys.executable)

**Comment by nixpal** [comment]
try also to remove and just install the engine using 
pip3 install keystone-engine
let me know if that works

**Comment by Y5neKO** [comment]
Oh, that solved the problem, thank you bro
![image](https://github.com/user-attachments/assets/995210c2-308a-4de8-a368-36b8b32e9b46)

**Comment by Y5neKO** [comment]
> try also to remove and just install the engine using pip3 install keystone-engine let me know if that works

Oh, that solved the problem, thank you bro
![image](https://github.com/user-attachments/assets/639ecc0c-7fdb-4a96-bc78-995d7e68f4c0)

**Comment by nixpal** [comment]
Awesome
